<?php
$typeArr[2] = '法律顾问';
$typeArr[9] = '在线法律咨询';
$typeArr[10] = '拟审合同';
$typeArr[11] = '创业经营';
$typeArr[12] = '劳动人事';
$typeArr[13] = '婚姻家庭';
$typeArr[14] = '打官司';
$typeArr[15] = '法律咨询';
$typeArr[16] = '找律师';
$typeArr[17] = '劳动仲裁';
$typeArr[18] = '债务纠纷';
$typeArr[19] = '房产纠纷';
$typeArr[20] = '合同纠纷';
$typeArr[21] = '起诉离婚';
$typeArr[22] = '交通事故';
$typeArr[23] = '刑事辩护';
$typeArr[24] = '知识产权';
$typeArr[25] = '人身损害';
$typeArr[26] = '其他纠纷';
?>