<li class="clearfix">
                            <div class="hb-right"> </div>
                            <a href="[field:arcurl/]" class="law-photo" target="_blank"><img src="[field:picname/]" alt="[field:title/]" /></a>
                            <div class="fl">
                                <p> <a href="[field:arcurl/]" class="f16 s-c333 fb" target="_blank">[field:title/]</a><i title="[field:title/]" class="ico-new i-new63"></i> [field:tag/]<!--<span class="law-bq">有团队</span><span class="law-bq">办过大案</span>--> </p>
                                <div class="mt5 clearfix">
                                    <div class="w325 fl">
                                        <p>擅长：[field:skill/]</p>
                                        <p class="mt5"> <em class="law-qg">特色律所</em> <a href="[field:arcurl/]" target="_blank">[field:addr/]</a> </p>
                                        <p class="s-c999 mt5"><i class="ico-lr i-place mr5"></i>[field:address/]</p>
                                    </div>
                                    <div class="w373 fl">
                                        <p><span class="mr20">案例：[field:cases/]</span><span>帮助：[field:helps/]</span></p>
                                        <p class="mt15 clearfix"> <span class="law-tel"><i class="ico-new i-new79"></i>[field:tel/]</span> <a href="/swt/" target="_blank" class="btn btn-gn2">在线咨询</a> </p>
                                    </div>
                                </div>
                                <div class="mt15 clearfix lh24">
                                    <div class="law-ensure pr fl mr30">
                                    [field:star runphp='yes']
                                    echo str_repeat('<i class="ico-ft i-sr14 i-sr14-oe"></i>',4);
                                    [/field:star]
                                    <!--<?php echo str_repeat('<i class="ico-ft i-sr14 i-sr14-oe"></i>',4); ?>-->
									<em class="f24">[field:star/]</em> </div>
                                    <span title="执业认证" class="s-c999 mr20"><i class="ico-new i-new73 mr5"></i>执业认证</span> </div>
                            </div>
                        </li>