<div class="wz-zhengwen">
      <h3><span class="chengdi"></span><a target="_blank" href="[field:arcurl/]">[field:title/]</a></h3>
      <p><a target="_blank" href="[field:arcurl/]">[field:description/]</a></p>
      <h4>分类：<a href="[field:arcurl/]">[field:typename/]</a><span class="jiange">阅读：[field:click/]次</span>
        <time>[field:pubdate function="GetDateTimeMK(@me)"/]</time>
      </h4>
    </div>