-->
                    <div class="choose-block">
                        <div class="city-bar">
                            <div class="title-part">
                                <h3>所在城市：</h3>
                            </div>
                            <div class="content-part"> 
                             {dede:php}AddFilter(3,1,'fenleia,fenleib,fenleic');{/dede:php}
                              <!--[field:linkallplace/]
								<select id="province" onchange="provinceSelect('1')">
                                    <option value="">选择省份 </option>
                                    [field:nativeplace /]
                                </select>
                                <select id="city" onchange="citySelect()">
                                    <option value="all">选择县市 </option>
                                    <option selected="selected" value="shanghai"> 上海市辖区 </option>
                                    <option value="" > 县 </option>
                                </select>-->
                            </div>
                        </div>
                        <div class="special-bar">
                            <div class="title-part">
                                <h3>专长领域：</h3>
                            </div>
                            <div class="content-part"> <a class="selected" href="/zhaolvshi/shanghai/all/all/p1.html" ><b>不限</b></a> <a class="" href="/zhaolvshi/shanghai/laodongzhongcai/all/p1.html" >劳动仲裁</a> <a class="" href="/zhaolvshi/shanghai/zhaiwujiufen/all/p1.html" >债务纠纷</a> <a class="" href="/zhaolvshi/shanghai/hetongjiufen/all/p1.html" >合同纠纷</a> <a class="" href="/zhaolvshi/shanghai/qisulihun/all/p1.html" >起诉离婚</a> <a class="" href="/zhaolvshi/shanghai/jiaotongshigu/all/p1.html" >交通事故</a> <a class="" href="/zhaolvshi/shanghai/renshensunhai/all/p1.html" >人身损害</a> <a class="" href="/zhaolvshi/shanghai/fangchanjiufen/all/p1.html" >房产纠纷</a> <a class="" href="/zhaolvshi/shanghai/xingshibianhu/all/p1.html" >刑事辩护</a> <a class="" href="/zhaolvshi/shanghai/zhishichanquan/all/p1.html" >知识产权</a> <a class="" href="/zhaolvshi/shanghai/qita/all/p1.html" >其他纠纷</a> </div>
                        </div>
                        <div class="year-bar">
                            <div class="title-part">
                                <h3>执业年限：</h3>
                            </div>
                            <div class="content-part" style="border-bottom: none;"> [field:years /]<!--<a href="/zhaolvshi/shanghai/all/all/p1.html" class="selected"><b>不限</b></a> <a href="/zhaolvshi/shanghai/all/1/p1.html" class="">1-5年</a> <a href="/zhaolvshi/shanghai/all/2/p1.html" class="">6-10年</a> <a href="/zhaolvshi/shanghai/all/3/p1.html" class="">10年以上</a>--> </div>
                        </div>
                    </div>
                    <!--