<div class="w280 mr20 fl">
						{dede:arclist flag='p' row='1'}
                       <a target="_blank" title="[field:title/]" href="[field:arcurl/]" class="pic-item h184"><img src="[field:picname/]" alt="[field:title/]" style="width: 280px;height: 184px;"><span>[field:title/]</span></a>
                       {/dede:arclist}
                        <ul class="art-list mt10">
							{dede:arclist row='4'}
                            <li><i class="ico-law i-law184 mr10"></i><a target="_blank" href="[field:arcurl/]">[[field:typename/]]</a><a target="_blank" href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></li>
                            {/dede:arclist}
                        </ul>
                    </div>