<?php
$z[0]=Array("arclist","\r\n                       <a target=\"_blank\" href=\"[field:arcurl/]\" class=\"pic-item h184\"><img src=\"[field:picname/]\" alt=\"[field:title/]\" style=\"width: 280px;height: 184px;\"><span>[field:title/]</span></a>\r\n                       ",34,310);
$z[0][4]=array();
$z[0][4]['flag']="p";
$z[0][4]['row']="1";
$z[1]=Array("arclist","\r\n                            <li><i class=\"ico-law i-law184 mr10\"></i><a target=\"_blank\" href=\"[field:arcurl/]\">[[field:typename/]]</a><a target=\"_blank\" href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n                            ",371,639);
$z[1][4]=array();
$z[1][4]['row']="4";

?>