<li>
                                <p><a target="_blank" href="[field:arcurl/]">[field:title/]</a><br />
                                    帮助人数：[field:helps/]</p>
                                <div class="img-part p-a"> <a target="_blank" href="[field:arcurl/]"><img src="[field:picname/]" alt="[field:title/]" /></a> </div>
                            </li>
                            {/dede:arclist}
                        </ul>
                        <!-- 帮助人数end --> 
                        <!-- 新入驻start -->
                        <ul class="list-unstyled" style="display: none;">
                            {dede:arclist typeid='16' row='4'}
                            <li>
                                <p><a target="_blank" href="[field:arcurl/]">[field:title/]</a><br />
                                    帮助人数：[field:helps/]</p>
                                <div class="img-part p-a"> <a target="_blank" href="[field:arcurl/]"><img src="[field:picname/]" alt="[field:title/]" /></a> </div>
                            </li>
                            {/dede:arclist}
                        </ul>
                        <!-- 新入驻end --> 
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{dede:include filename='footer.htm'