<?php
$z[0]=Array("global","(@me==1)? @me='':@me='mt20';",24,109);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",136,151);
$z[1][4]=array();
$z[2]=Array("picname","",179,195);
$z[2][4]=array();
$z[3]=Array("title","",202,216);
$z[3][4]=array();
$z[4]=Array("arcurl","",292,307);
$z[4][4]=array();
$z[5]=Array("title","",316,330);
$z[5][4]=array();
$z[6]=Array("title","",351,365);
$z[6][4]=array();
$z[7]=Array("info","",430,443);
$z[7][4]=array();

?>