<div class="lore-r-item [field:global name=autoindex runphp='yes'](@me==1)? @me='':@me='mt20';[/field:global]"><a target="_blank" href="[field:arcurl/]" class="fl mr10"><img src="[field:picname/]" alt="[field:title/]"></a>
                            <p class="h20"><a target="_blank" href="[field:arcurl/]" title="[field:title/]" class="f14 s-c333">[field:title/]</a></p>
                            <p class="h40 s-c999 mt10">[field:info/]…</p>
                        </div>