<field:body itemname="详细介绍" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="split">
</field:body>	
<field:price itemname="市场价" autofield="1" notsend="0" type="float" isnull="true" islist="1" default=""  maxlength="" page="">	
</field:price>	
<field:trueprice itemname="现价" autofield="1" notsend="0" type="float" isnull="true" islist="1" default=""  maxlength="" page="">	
</field:trueprice>	
<field:oneday itemname="一个工作日" autofield="1" notsend="0" type="float" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:oneday>
<field:jiaji itemname="合同加急" autofield="1" notsend="0" type="float" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:jiaji>
<field:units itemname="计量单位" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">	
</field:units>		
<field:uptime itemname="上架时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">	
</field:uptime>	
