<?php
$z[0]=Array("linkallplace","",289,311);
$z[0][4]=array();
$z[1]=Array("channelid","",373,391);
$z[1][4]=array();
$z[2]=Array("typeid","",392,407);
$z[2][4]=array();
$z[3]=Array("topplace","",472,490);
$z[3][4]=array();
$z[4]=Array("nativeplace","",656,677);
$z[4][4]=array();
$z[5]=Array("linkalltype","",2240,2260);
$z[5][4]=array();
$z[6]=Array("infotype","",2261,2279);
$z[6][4]=array();

?>