<div class="search-result">
                        <ul>
                            <li>
                                <p class="name"> <a href="[field:arcurl/]"> [field:title/] </a> </p>
                                <p  class="grey2 lh25">[field:typename/]</p>
                                <p class="lh25">[field:description/]... </p>
                            </li>
                        </ul>
                    </div>