<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",16,170);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",186,201);
$z[1][4]=array();
$z[2]=Array("title","",217,231);
$z[2][4]=array();
$z[3]=Array("pubdate","",293,339);
$z[3][4]=array();
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("trueprice","",371,389);
$z[4][4]=array();
$z[5]=Array("brand","",421,435);
$z[5][4]=array();
$z[6]=Array("click","",467,481);
$z[6][4]=array();
$z[7]=Array("description","",527,547);
$z[7][4]=array();

?>