<?php
$z[0]=Array("global","",144,169);
$z[0][4]=array();
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",426,452);
$z[1][4]=array();
$z[1][4]['name']="cfg_cmspath";
$z[2]=Array("arclist","\r\n                                <p><a href=\"[field:arcurl/]\" class=\"lianjie\" target=\"_blank\">[field:title/]</a></p>\r\n                                ",1872,2072);
$z[2][4]=array();
$z[2][4]['typeid']="11";
$z[2][4]['row']="6";
$z[3]=Array("arclist","\r\n                                <p><a href=\"[field:arcurl/]\" class=\"lianjie\" target=\"_blank\">[field:title/]</a></p>\r\n                                ",2222,2422);
$z[3][4]=array();
$z[3][4]['typeid']="12";
$z[3][4]['row']="6";
$z[4]=Array("arclist","\r\n                                <p><a href=\"[field:arcurl/]\" class=\"lianjie\" target=\"_blank\">[field:title/]</a></p>\r\n                                ",2572,2772);
$z[4][4]=array();
$z[4][4]['typeid']="13";
$z[4][4]['row']="6";
$z[5]=Array("arclist","\r\n                                <p><a href=\"[field:arcurl/]\" class=\"lianjie\" target=\"_blank\">[field:title/]</a></p>\r\n                                ",2919,3119);
$z[5][4]=array();
$z[5][4]['typeid']="14";
$z[5][4]['row']="6";
$z[6]=Array("channelartlist","\r\n                                <p><a href=\"{dede:field.typeurl/}\" class=\"lianjie\" target=\"_blank\">{dede:field.typename/}</a></p>\r\n                                ",4191,4425);
$z[6][4]=array();
$z[6][4]['typeid']="17,18,19";
$z[6][4]['row']="3";
$z[7]=Array("channelartlist","\r\n                                <p><a href=\"{dede:field.typeurl/}\" class=\"lianjie\" target=\"_blank\">{dede:field.typename/}</a></p>\r\n                                ",4496,4730);
$z[7][4]=array();
$z[7][4]['typeid']="20,21,22";
$z[7][4]['row']="3";
$z[8]=Array("channelartlist","\r\n                                <p><a href=\"{dede:field.typeurl/}\" class=\"lianjie\" target=\"_blank\">{dede:field.typename/}</a></p>\r\n                                ",4801,5035);
$z[8][4]=array();
$z[8][4]['typeid']="23,24,25";
$z[8][4]['row']="3";
$z[9]=Array("php"," echo \$solvenum['solved']; ",8147,8195);
$z[9][4]=array();

?>