<?php
$z[0]=Array("arclist","\r\n                            <p><a href=\"[field:arcurl/]\" class=\"lianjie\" target=\"_blank\">[field:title/]</a></p>\r\n                            ",2507,2699);
$z[0][4]=array();
$z[0][4]['typeid']="11";
$z[0][4]['row']="6";
$z[1]=Array("arclist","\r\n                            <p><a href=\"[field:arcurl/]\" class=\"lianjie\" target=\"_blank\">[field:title/]</a></p>\r\n                            ",2837,3029);
$z[1][4]=array();
$z[1][4]['typeid']="12";
$z[1][4]['row']="6";
$z[2]=Array("arclist","\r\n                            <p><a href=\"[field:arcurl/]\" class=\"lianjie\" target=\"_blank\">[field:title/]</a></p>\r\n                            ",3167,3359);
$z[2][4]=array();
$z[2][4]['typeid']="13";
$z[2][4]['row']="6";
$z[3]=Array("arclist","\r\n                            <p><a href=\"[field:arcurl/]\" class=\"lianjie\" target=\"_blank\">[field:title/]</a></p>\r\n                            ",3494,3686);
$z[3][4]=array();
$z[3][4]['typeid']="14";
$z[3][4]['row']="6";
$z[4]=Array("channelartlist","\r\n                            <p><a href=\"{dede:field.typeurl/}\" class=\"lianjie\" target=\"_blank\">{dede:field.typename/}</a></p>\r\n                            ",4521,4747);
$z[4][4]=array();
$z[4][4]['typeid']="17,18,19";
$z[4][4]['row']="3";
$z[5]=Array("channelartlist","\r\n                            <p><a href=\"{dede:field.typeurl/}\" class=\"lianjie\" target=\"_blank\">{dede:field.typename/}</a></p>\r\n                            ",4814,5040);
$z[5][4]=array();
$z[5][4]['typeid']="20,21,22";
$z[5][4]['row']="3";
$z[6]=Array("channelartlist","\r\n                            <p><a href=\"{dede:field.typeurl/}\" class=\"lianjie\" target=\"_blank\">{dede:field.typename/}</a></p>\r\n                            ",5107,5333);
$z[6][4]=array();
$z[6][4]['typeid']="23,24,25";
$z[6][4]['row']="3";

?>