<?php
$z[0]=Array("global","",226,252);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",296,326);
$z[1][4]=array();
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",363,390);
$z[2][4]=array();
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1257,1294);
$z[3][4]=array();
$z[3][4]['filename']="header.htm";
$z[4]=Array("arclist","\r\n			{\r\n				item:\"[field:title/]\",\r\n				url:\"[field:arcurl/]\"\r\n			},\r\n		",25018,25140);
$z[4][4]=array();
$z[4][4]['typeid']="11";
$z[4][4]['row']="10";

?>