<?php
$z[0]=Array("list","\r\n                                <li class=\"p-r\"> <span class=\"p-a w5-5\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span>\r\n                                <div class=\"dot p-a\"></div>\r\n                                <h3 class=\"w4\"> <a class=\"text-darkgray\" href=\"[field:arcurl/]\">[field:title/]</a></h3>\r\n                            </li>\r\n                                ",40425,40841);
$z[0][4]=array();
$z[0][4]['pagesize']="10";
$z[1]=Array("pagelist","",41013,41084);
$z[1][4]=array();
$z[1][4]['listitem']="info,index,end,pre,next,pageno";
$z[1][4]['listsize']="5";

?>