<?php
$z[0]=Array("global","",3581,3636);
$z[0][4]=array();
$z[0][4]['name']="keyword";
$z[0][4]['function']="RemoveXSS(@me)";
$z[1]=Array("global","",4384,4439);
$z[1][4]=array();
$z[1][4]['name']="keyword";
$z[1][4]['function']="RemoveXSS(@me)";
$z[2]=Array("list","\r\n                    <div class=\"search-result\">\r\n                        <ul>\r\n                            <li>\r\n                                <p class=\"name\"> <a href=\"[field:arcurl/]\"> [field:title/] </a> </p>\r\n                                <p  class=\"grey2 lh25\">[field:typename/]</p>\r\n                                <p class=\"lh25\">[field:description/]... </p>\r\n                            </li>\r\n                        </ul>\r\n                    </div>\r\n                    ",4557,5080);
$z[2][4]=array();
$z[2][4]['perpage']="20";
$z[3]=Array("pagelist","",5206,5235);
$z[3][4]=array();
$z[3][4]['listsize']="4";

?>