<?php  exit();
/*
Page: /dede/ask_type.php
Error: Table 'lawyer.dede_asktype' doesn't exist <br />Error sql: <font color='red'>select * from `dede_asktype` order by disorder asc, id asc</font>
Time2018-07-02 15:42:00
*/
?>
<?php  exit();
/*
Page: /dede/ask_admin.php
Error: Table 'lawyer.dede_asktype' doesn't exist <br />Error sql: <font color='red'>select id, reid from `dede_asktype` </font>
Time2018-07-02 15:42:07
*/
?>
<?php  exit();
/*
Page: /dede/ask_admin.php
Error: Table 'lawyer.dede_ask' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_ask`  where  status>=-1 LIMIT 0,1;</font>
Time2018-07-02 15:42:07
*/
?>
<?php  exit();
/*
Page: /dede/ask_admin.php
Error: Table 'lawyer.dede_ask' doesn't exist <br />Error sql: <font color='red'>select * from `dede_ask`  where  status>=-1  order by id desc LIMIT 0,20</font>
Time2018-07-02 15:42:07
*/
?>
<?php  exit();
/*
Page: /dede/ask_answer.php
Error: Table 'lawyer.dede_asktype' doesn't exist <br />Error sql: <font color='red'>select id, reid from dede_asktype</font>
Time2018-07-02 15:42:11
*/
?>
<?php  exit();
/*
Page: /dede/ask_answer.php
Error: Table 'lawyer.dede_askanswer' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_askanswer` where  ifcheck>=0 LIMIT 0,1;</font>
Time2018-07-02 15:42:11
*/
?>
<?php  exit();
/*
Page: /dede/ask_answer.php
Error: Table 'lawyer.dede_askanswer' doesn't exist <br />Error sql: <font color='red'>select * from `dede_askanswer` where  ifcheck>=0 order by id desc LIMIT 0,20</font>
Time2018-07-02 15:42:11
*/
?>
<?php  exit();
/*
Page: /dede/ask_admin.php
Error: Table 'lawyer.dede_asktype' doesn't exist <br />Error sql: <font color='red'>select id, reid from `dede_asktype` </font>
Time2018-07-02 15:42:14
*/
?>
<?php  exit();
/*
Page: /dede/ask_admin.php
Error: Table 'lawyer.dede_ask' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_ask`  where  status>=-1 LIMIT 0,1;</font>
Time2018-07-02 15:42:14
*/
?>
<?php  exit();
/*
Page: /dede/ask_admin.php
Error: Table 'lawyer.dede_ask' doesn't exist <br />Error sql: <font color='red'>select * from `dede_ask`  where  status>=-1  order by id desc LIMIT 0,20</font>
Time2018-07-02 15:42:14
*/
?>
